# Generated by Django 4.1.6 on 2023-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_nbr',
            field=models.IntegerField(unique=True),
        ),
    ]
