# Generated by Django 4.1.6 on 2023-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='medical_history',
            field=models.TextField(),
        ),
    ]
