# Generated by Django 4.1.6 on 2023-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doseOne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='doseOneDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='doseTwo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='doseTwoDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nextAppointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
