# Generated by Django 4.1.6 on 2023-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_phone_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doseOneTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='doseTwoTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
