# Generated by Django 4.1.6 on 2023-04-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_doseonetime_account_dosetwotime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nextAppointment',
        ),
    ]
